### ISSUE TITLE
feature request: certificate functionality

### ISSUE THREAD

**Issue by kphunter** [rhtconsulting/ansible-role_haproxy#2]
It would be great if there was the capability to add a cert/key file per application. Perhaps something like: 
```
- name: consul
  domain: sub.consul.internal
  expose_https: true
  redirect_http_to_https: true
  cert-key-file: star-consul-internal.pem
  servers:
    - name: consul-server-one
      address: 10.0.42.3
      port_https: 8501

```
